project:
  type: website
  output-dir: docs

website:
  title: "STM"
  favicon: favicon.png
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: experience.qmd
        text: Experience
      - href: teaching.qmd
        text: Teaching
    collapse: true
    search: true
    background: primary
    back-to-top-navigation: true
    page-footer: "Copyright 2024, Sitao Min"
    max-width: 1500px
    pinned: true

format:
  html:
    theme: flatly
    page-layout: full
    css: styles.css
    toc: false
    fontsize: 1.1em
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px

editor: visual

