project:
  type: website
  output-dir: docs

website:
  title: "STM"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: experience.qmd
        text: Experience
      - href: software.qmd
        text: Software
    collapse: true
    search: false
    background: primary
    back-to-top-navigation: true
    page-footer: "Copyright 2024, Sitao Min" 

format:
  html:
    theme:
        light: sandstone
        dark: darkly
    css: styles.css
    toc: false

editor: visual

