project:
  type: website
  output-dir: docs

website:
  title: "STM"
  favicon: favicon.png
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: experience.qmd
        text: Experience
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects & Software
      - href: teaching.qmd
        text: Teaching
    collapse: true
    search: true
    background: dark
    back-to-top-navigation: true
    page-footer: "Copyright 2024, Sitao Min"
    max-width: 1500px
    pinned: true

format:
  html:
    theme: cosmo
    page-layout: full
    css: styles.css
    toc: false
    fontsize: 1.2em
    include-in-header: "_includes/header.html"
    anchor-sections: false
    link-external-icon: false
    link-external-newwindow: true
    grid:
      sidebar-width: 0px
      body-width: 950px
      margin-width: 0px

editor: visual

