---
toc: false
format:
    html:
        css: style.css
        grid:
            sidebar-width: 0px
            body-width: 800px
            margin-width: 0px
---

<style>
.project { font-size: 0.9rem !important; }
</style>

### Projects

---

:::: experience-container
::: project
**Post-HCT Survival Predictions using ML/DL, Kaggle CMBTR Challenge, Silver Medal (74/3084), 2025**

-   Proposed ensembles of deep survivor models and XGBoost-based Cox survival using pseudo label techniques for survival risk prediction for hematopoietic cell transplant patients.
:::
::::

:::: experience-container
::: project
**Predict Protein-molecule Interaction for New Medicines using Deep Learning, Kaggle Challenge, Bronze Medal (178/1950), 2024**

-   Processed protein data for molecule representation extraction using Pandas and BELKA and developed 1D CNN model in PyTorch for protein-molecule interaction prediction.
:::
::::

:::: experience-container
::: project
**Financial Crime Prevention using Secure AI, US PETs Challenge, 1st Place (1/60), 2024**

-   Designed privacy-preserving federated XGBoost using Bloomfilter for financial crime detection.
-   **Challenge Report: [US-UK PETs Challenge](https://www.nist.gov/itl/applied-cybersecurity/privacy-engineering/collaboration-space/challenges/us-uk-pets-prize){target="_blank"} \| Solution: [Scarlet-PETs](https://github.com/usnistgov/PrivacyEngCollabSpace/tree/master/tools/de-identification/Scarlet-PETs){target="_blank"}**
:::
::::